# =============================================================================
# payments-core sidecar image — multi-stage, distroless runtime.
# -----------------------------------------------------------------------------
# Stage 1 (builder): installs dev + runtime deps, generates proto stubs,
#                    compiles TypeScript to dist/, prunes dev deps.
# Stage 2 (runtime): distroless Node 20, non-root, only dist + prod deps.
#
# Final image size target: < 150 MB. Distroless base is ~120 MB; dist/ and
# @grpc/grpc-js + pino stay well under 30 MB combined.
# =============================================================================

FROM node:20-slim AS builder
WORKDIR /app

# Corepack pulls the exact pnpm version declared in package.json.
RUN corepack enable

# Install dependencies first for Docker layer caching.
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy source + proto + config.
# NOTE: `src/generated/` MUST be generated by the host (`pnpm proto:generate`)
# before `docker build` runs. The build stage does not invoke buf because the
# buf.build plugin registry is not reliably reachable from every CI network.
# The `prebuild` script is bypassed via `--ignore-scripts`-style flow by
# invoking `tsc` directly instead of `pnpm build`.
COPY proto ./proto
COPY src ./src
COPY tsconfig.json tsconfig.build.json ./
COPY openapi ./openapi

# Compile TypeScript. `src/generated/` is present from the host.
RUN pnpm exec tsc -p tsconfig.build.json

# Drop dev dependencies so the runtime stage copies only production packages.
RUN pnpm prune --prod


FROM gcr.io/distroless/nodejs20-debian12 AS runtime
WORKDIR /app

# Distroless ships a `nonroot` (uid 65532) user by default.
USER nonroot

COPY --from=builder --chown=nonroot:nonroot /app/dist ./dist
COPY --from=builder --chown=nonroot:nonroot /app/node_modules ./node_modules
COPY --from=builder --chown=nonroot:nonroot /app/package.json ./package.json

EXPOSE 50051
ENV NODE_ENV=production \
    GRPC_PORT=50051 \
    LOG_LEVEL=info

CMD ["dist/main.js"]
